### PR TITLE
Fixed initial table sort by scenario.name in scenario table in usecase.js

### PR DESCRIPTION
**Pull request by patrickschweizer**
…Case.js

### CODE REVIEW

**Comment by bruderol** [comment]
@adiherzog @patrickschweizer 
If I understand this right, this is a fix, that we should merge into the release 2.2 - @adiherzog do you agree, if we merge that small fix?

**Comment by bruderol** [comment]
@adiherzog I will merge that now. Think it is okay.

**Comment by adiherzog** [comment]
Thanks for the fix and for merging. Looks good :+1:

**Comment by bruderol** [comment]
Tataaaaa .... ready for the release :+1:

**Pull request merged**
