### PR TITLE
Feature/598 make java8 work using updated elasticsearch

### PR DESCRIPTION
**Pull request by bruderol**
@cgrossde @eggerschwiler related to #598 and #616 

In this PR you can see what I did so far to get it working with RestEasy 3.
The merge goes to your branch #685 - not to develop yet - such that you can review my changes and profit from my improvements.

Auf diesem Branch sind jetzt nur noch 16 Tests gefailed. Ich vermute noch aus drei Gründen:

1. RestEasy Path Konflikte: neue Version interpretiert @Path teilweise anders ---> man sollte jetzt im Server Log entsprechende Fehlermeldungen sehen (dank den hinzugefügten ExceptionHandlern).

2. Teilweise werden Collections in RestEasy 3 anders serialisiert, wenn sie nur mit @XmlElement annotiert wurden --> z.B. "labels" (ev. ausschliesslich?) kommen anders im Frontend an, gewisse Tests failen deshalb, ich habe das partiell gefixt. Hier ist zu überlegen ob wir die `scenarioo-java` fixen wollen (Achtung: Xml-Format darf nicht gebrochen werden!) oder den angefangenen Weg (im Frontend anpassen) weiterführen wollen.

3. Fehlender Elasticsearch 5 Cluster mit Name "elasticsearch" auf CI --> Full Text Search e2e tests gebrochen.

### CODE REVIEW

**Comment by eggerschwiler** [comment]
@bruderol Should we keep this branch for further experiments without Docker?

**Comment by bruderol** [comment]
@eggerschwiler yes, exactly - there is currently one small difference on that branch, it goes against elasticsearch on localhost (not in docker cluster), because this branch has not that one change from the other branch.

Thanks for review and merging.

Still we have to decide whether my changes regarding the changed labels collection could be addressed differently as well.

**Comment by bruderol** [comment]
@eggerschwiler yes, exactly - there is currently one small difference on that branch, it goes against elasticsearch on localhost (not in docker cluster), because this branch has not that one change from the other branch.

Thanks for review and merging.

Still we have to decide whether my changes regarding the changed labels collection could be addressed differently as well.

**Comment by bruderol** [comment]
@eggerschwiler yes, exactly - there is currently one small difference on that branch, it goes against elasticsearch on localhost (not in docker cluster), because this branch has not that one change from the other branch.

Thanks for review and merging.

Still we have to decide whether my changes regarding the changed labels collection could be addressed differently as well.

**Pull request merged**
