### PR TITLE
546-added-steps

### PR DESCRIPTION
**Pull request by danielsuter**
#546 An added label is shown on the scenario overview, if the complete scenario was added.
Step diff data is queried serially, because we don't know if the whole scenario was added before.
Also contains version upgrades for protractor.

### CODE REVIEW

**Comment by bruderol** [comment]
@danielsuter I do not get it, why this was so difficult to realize, the step page allready displayed the same label before. Is it there solved in the same way (allways having to check for the use case or scenario is an added one)? Shouldnt the service allready return the right diff info for such steps?

**Comment by danielsuter** [comment]
@bruderol The amount of calls stay the same, so I don't really understand your comment.
We know this information in the use case overview page, but not in the scenario overview.

In the step page, the following is done:
1. Load diff info
2. On failure, assume it's added.
This works but results in an error 500 printed on the console, which is not a good solution. We don't have another option there though.

Another difference is, that we only have a step scope on the step overview. Pages don't matter.

**Comment by bruderol** [comment]
ok, allright, I was just surprised. But ok, that looks good to me, as long as it works.

**Comment by danielsuter** [comment]
It would be possible but the solution is not clean as it results in errors on our console. We can't get rid of that one, because it's framework code. Imho my solution is cleaner but it would result in another call on the step page.

**Comment by bruderol** [comment]
ok, let's just leave it like that then. Should I merge or will you do so?

**Comment by danielsuter** [comment]
I'll leave the honour to you :-)

**Pull request merged**
