### PR TITLE
02 - Feature/#692 Create DiffViewer Comparison Dialog

### LINKED ISSUE #692: Diff Viewer Plus: Create Comparisons Manually through Dialog
Offer a dialogue "Create Comparison ..." on all pages in the breadcrumbs navigation, similar to sketcher, such that the user can create new comparisons manually.

## Acceptance Criteria
* [x] user can select "Create Comparison ..." button on all pages in breadcrumbs area to start creating a new comparison to be calculated
       * the button is styled in such a way that people recognize it as a important new feature, not as light as the sketcher button that nobody has seen and therefroe used ever
       * sketcher button style is adjusted to have same new style
* [x] in the dialogue the user can select to which branch to compare the current branch
* [x] if the user selects a branch to which a comparison already exists, he is informed about the fact that this is already present
* [x] the user can select a name for the comparison
       * name is validated to be unique against existing comparisons on same build
* [x] the dialogue also contains a short explanation, that the comparison will be calculated in the backgrond and should appear in the comparison dropdown once the comparison has been calculated 
* [x] the dialogue also contains a link to the comparison tab where the user can see calculation state of all comparisons available.
* [x] the dialogue also contains a short hint, that comparisons can be configured to be calculated automatically on new build results and a link to the documentation where that is explained
* [x] tooltips are displayed to explain the values to be entered
* [x] when the dialog is submited and the creation of the comparison somehow fails a error message is displayed
* [x] if the creation request was sent sucessfully the dialog is closed
* [x] DiffViewer Documentation was updated

## UI Mockups 

Buttons:
image

Dialog
image

Dialog with Validation on Submit (and partialy on changes in dialog)
image

### PR DESCRIPTION
**Pull request by bruderol**
Fixes #692 Dialog to Create a Comparison manually from Frontend.

You can test the new feature here on the demo:
http://demo.scenarioo.org/scenarioo-feature-692-create-comparison-dialogue

To be reviewed only after PR #684 is merged first! Once the other PR is merged you should only see remaining changes on this PR to be merged (if not, we can reopen a new PR).

Also includes other improvements, like:
* update and clean up diff viewer documentation (reduce to one user guide, remove unnecessary documentation)
* new states for comparisons (QUEUED_FOR_PROCESSING - for comparisons waiting for calculation, SKIPPED for comparisons that can not be compared because no build is available to compare to)
* removing asynch write for DiffViewer data (caused some concurrency problems, diff data is written in separate thread anyway)
* Fix saving of BuildDiffInfo to be multi threading save (otherwise data was corrupted sometimes, when playing around with the new features)
* fixing some tooltips (were using "tooltip" instead of "uib-tooltip") and improving some tooltip texts
* get rid of "Meta Data" in UI (consequently call it "Details")
* fix before silently ignored null pointer exceptions in tests, because before those exceptions were asynchronously and not checked for.

This PR is based on changes from #684.

### CODE REVIEW

**Comment by adiherzog** [comment]
@bruderol I see that PR #684 which is the basis for this one is merged. I still see 69 commits and 90 changed files though. Is this correct or does this also include changes from #684 that are already reviewed and merged?

**Comment by adiherzog** [comment]
@bruderol This branch led to problems on the develop demo instance. Exception in logs:

```
INFO  ScenarioDocuBuildsManager     :   Processing documentation content data in directory: /var/lib/scenarioo/data/develop
INFO  ScenarioDocuBuildsManager     : Updating the list of available builds and their states ...
ERROR ScenariooWebApplication       : ====================================================
ERROR ScenariooWebApplication       : Error during Scenarioo startup
java.lang.RuntimeException: Could not unmarshall /var/lib/scenarioo/data/develop/scenarioo-feature-692-create-comparison-dialogue/branch.xml
        at org.scenarioo.api.util.xml.ScenarioDocuXMLFileUtil.unmarshal(ScenarioDocuXMLFileUtil.java:69)
        at org.scenarioo.api.util.xml.ScenarioDocuXMLFileUtil.unmarshalListOfFiles(ScenarioDocuXMLFileUtil.java:84)
        at org.scenarioo.api.ScenarioDocuReader.loadBranches(ScenarioDocuReader.java:57)
        at org.scenarioo.business.builds.ScenarioDocuBuildsManager.loadBranchBuildsList(ScenarioDocuBuildsManager.java:204)
```

Therefore I deleted the folder `/var/lib/scenarioo/data/develop/scenarioo-feature-692-create-comparison-dialogue`. Please make sure this does not break the demo instance before you execute the next build of this branch. Thanks.

**Comment by bruderol** [comment]
@adiherzog 

1. yeah, you are right, you still see all changes. Bad, other git web frontends and Pr merging tools handle this better (e.g. bitbucket). I will open a new Pr with all my work I did for comparisons in one final PR.

2. The other issue you found: thanks for analysing! I think we have to fix this, it can not be that special branch names or inconsistencies in scenarioo data leads to crashing scenarioo. It might even be that this has allready been fixed on my other branch/PR where I optimized something regarding a issue with inconsistencies regarding branch names to at least not crash the server on startup..

**Comment by bruderol** [comment]
replaced by #701

**Comment by bruderol** [comment]
replaced by #701

**Pull request closed without merging**
