### PR TITLE
#477 only create directories when they are realy needed (on persistin…

### PR DESCRIPTION
**Pull request by bruderol**
…g one of the files) in SketcherFiles (or DesignFiles ?? ---> also contains review comments for inconsistent naming issue #478)

### CODE REVIEW

**Comment by bruderol** [comment]
I merged it to get a new release candidate for testing it in my project.

@adiherzog you can still review my changes on the PR and give me feedback. 
You can delete the branch when reviewed.
Thank you.

**Comment by bruderol** [comment]
@adiherzog @danielsuter this would have been the PR with the fix for the windows pathes. Let us more regularly merge from release to master to avoid such conflicts in future.

**Comment by danielsuter** [comment]
Did you merge it into develop and the release branch? Otherwise we will lose the changes.

**Comment by bruderol** [comment]
@danielsuter yes, of course ... see other PR of some days ago ... You can merge from release2.2 to develop, whenever you like. We will also do it from time to time and especially when the release is done.

**Pull request merged**
