### PR TITLE
#437 Add rest service to get screenshot urls for an object

### PR DESCRIPTION
**Pull request by Stivo**
This is the pull request for this issue:
https://github.com/scenarioo/scenarioo/issues/437 

Our requirements have changed again so we will need this. I cleaned up the code, got scenarioo to run again and tested it. It seems to work fine, tested with the url:
http://localhost:8000/scenarioo/rest/branch/wikipedia-docu-example/build/2014-03-19/screens/configuration/switch_language_config

which returns:
["rest/branch/wikipedia-docu-example/build/2014-03-19/usecase/Switch Language/scenario/search_article_in_german_and_switch_to_spanish/image/000.png","rest/branch/wikipedia-docu-example/build/2014-03-19/usecase/Switch Language/scenario/search_article_in_german_and_switch_to_spanish/image/001.png","rest/branch/wikipedia-docu-example/build/2014-03-19/usecase/Switch Language/scenario/search_article_in_german_and_switch_to_spanish/image/002.png","rest/branch/wikipedia-docu-example/build/2014-03-19/usecase/Switch Language/scenario/search_article_in_german_and_switch_to_spanish/image/003.png","rest/branch/wikipedia-docu-example/build/2014-03-19/usecase/Switch Language/scenario/search_article_in_german_and_switch_to_spanish/image/004.png"]

### CODE REVIEW

**Comment by bruderol** [comment]
@Stivo Thank you for your contribution!

In general your change looks good and useful and from my point of view, it can be merged.

Some thoughts and remarks to consider:

* @adiherzog I think it might be a good idea, and no risk at all, to take this change into the next release (which means also merging it to release branch!). This would have the advantage for @stivo that he can immediately use the new release with this new feature. What you think?

* @Stivo Can you please explain to us once what you need this service exactly for. Wouldn't it be a good idea for the future to have also a page (could replace the current generic object repository view) in scenarioo, where you can directly browse and see all the screenshots related to an object (e.g. all screenshots of a page). I think we need to plan implementing this. Such a view might also be helpful for the diff viewer ( @danielsuter ?).

* One point that might need improvement in the future: Instead of calculating all the screenshot URLs by loading all the step XMLs on the call to the rest service, we should instead calculate this information directly when the index files are generated and add this information to the steps, such that the images could also be easily displayed on such an object index view (see second point) in the future without the overhead to load all the step data. That last point would be very easy to change and we should plan this.

But as I said, for now, I think we can merge this. Thank you! :+1: 

@adiherzog can you shortly look at it and merge it? Maybe also to release?

**Comment by adiherzog** [comment]
@Stivo Thanks for the contribution. It looks good to me. The only thing that would be nice in addition would be a test that makes sure this feature does not break in the future. Do you have time to implement a test?

I see these options:

* Protractor test that calls the REST endpoint in the browser and asserts the JSON that is returned. This would be quite good for regression testing as it tests the feature end-to-end and it would also document it in our Scenarioo self-docu (even though it is not a UI feature and does not really belong there...).
* A JUnit test that tests the REST endpoint: This would be a nice option but it would require to extend our build scripts to add the ability to run JUnit tests agains the deployed Scenarioo demo.
* A unit test that just tests the logic. This would be quite some work as you would have to mock all the dependencies and add your own test data for it.

@Stivo @bruderol Which option would you prefer / like to implement?

I'm happy to merge it into release 2.2 if it's ready by the end of next week (April 8).

**Comment by bruderol** [comment]
Option 2 is a "no go" for me.
Option 1 and 2 would be okay for me.

I see a 4th option (as a general recommended option to test the server components):
* we do not need to mock all the dependencies
* instead we just need some example build files that are available for the junit tests as [test fixture](https://en.wikipedia.org/wiki/Test_fixture) such that we can easily test the server components (but without running the whole server container) to test that the component behave as expected, given it operates on a well known set of data. Usually we use the demo Data (wikipedia dummy example data that is also used in our demo and that is generated by our dummy test data generator).
I think we should write a junit test, that tests exactly what @Stivo described in the description of this merge request (well done @stivo :+1: ) as an example what the functionality does. This would be sufficient from my point of view to test this feature, such that we are quite sure that we won't break it in the future.

**Comment by bruderol** [comment]
Proposal: 
If @Stivo has no time to write a unit test fast. then just merge it to the release branch (and then the  develop as well!) and open an issue for adding a unit test. I think I might have some time to look at this. Should be very easy to write such a test as proposed above against the wikipedia test data files as fixtures that are allready there.

**Comment by Stivo** [comment]
We want to build a translation tool for SAM. It will be highly specific to SAM, directly work with git commits and know our internal structure of where translated text reside in the source. All the existing translation tools we found fail two of our requirements:

- They don't show multiple languages on the same screen, always just the master language and one more. We would like all 4 languages side by side to make sure the text contents match.
- None of them show a screenshot of the text in context. 

This rest service allows that tool to query scenarioo for all the screenshots where a specific text fragment is used. 

I have been thinking that maybe the URL still needs some tweaking, if you want to provide screenshots for features and use cases as well as mentioned by @bruderol earlier in #437.
Currently it is under screens/{objectType}/{objectId}, maybe it should be screens/object/{objectType}/{objectId}. So that would leave room for screens/feature/{featureName} etc. What do you think?

About testing: 

- Option 1: I guess I could write the protractor test
- Option 4: Would this test be the first of its kind? In that case it would be way harder for me to write the test than for you guys.

**Comment by bruderol** [comment]
Wow, very cool, that is a very good use case and demonstrates that it really makes sense that we have not just a web frontend but also a REST interface, such that other tools can be build on top of us. Cool :+1: I want see a demo of this tool, when you have it.

I not understand what you were talking about features.

I think the URL should be as follows:
/rest/branch/{branchName}/build/{buildName}/object/{type}/screenshots 

I just think that one possibility would have been to instead of build this separate service, to just add the URLs to the existing object index resource as image URLs during import instead of reading all the steps in this service on accessing it. But okay, let's keep it as it is for now. And open an issue to change this later.

Also I think, that we should also provide a view that shows all the images of a page or object directly. This should also go on this additional issue or maybe this issue is allready the same as #437 ??.

Proposal:
1. Let's change the URL as proposed by me and then let's merge it (without protractor test)
2. I can show you how to easily write a test, as proposed by me. I could even start it. Then you could finish it. We can do that after the merge and the merge should go to release branch. Ok?
3. Let's open an issue for changing the object index to contain step image URLs for better object index pages and to improve the object repository search result page accordingly to display the step images. We could realize this together with the full text search maybe or later.

**Comment by Stivo** [comment]
Sure, we will show you whatever we get running.

Sorry, I meant pages, scenarios and use cases, not features. The URLs should work for those as well. Putting screenshots at the end sounds good to me. So I assume something like this for the different types?
/rest/branch/{branchName}/build/{buildName}/object/{type}/screenshots
/rest/branch/{branchName}/build/{buildName}/scenario/{scenarioName}/screenshots
/rest/branch/{branchName}/build/{buildName}/page/{pageName}/screenshots
/rest/branch/{branchName}/build/{buildName}/useCase/{useCaseName}/screenshots

The proposal sounds good to me. If you get me started I can finish.

**Comment by bruderol** [comment]
Your first URL is wrong, because I also put it wrong before (sorry!), it has to be:
/rest/branch/{branchName}/build/{buildName}/object/{type}/{objectName}/screenshots

So for pages it will automatically work but under following URL:
/rest/branch/{branchName}/build/{buildName}/object/page/{pageName}/screenshots

For usecase and scenarios I am not sure if this makes sense to have this on the same REST service.The current REST resource does only expand to steps, if you searched something that was part of the step (e.g. a page or any other object, ...) and will only return those steps where what you searched for was attached on it. If we changed that, it would have to return all screenshots of all the scenarios of one use case, does that make realy sense?? you can click into the usecase and its scenarios to see all the screenshots allready. Can't you? 
That's why I think that for useCase and scenario we might have to look at it separately in case it is really needed and to put this on a special "/screenshots" service. But let us do that only if it is realy needed.

For all other objects the "/screenshots" would not be needed at all, if we simply include the screenshot URLs for all steps on the existing index service (by calculating it instead on generating this indexes).

**Comment by Stivo** [comment]
Well, you brought up the scenarioos in #437:
NEED 2: get all screenshots of all steps of a scenarioo (for protoyping in a tool)
But I agree, if it is not needed then lets not build it.

I think the URL's are good. If zip files are also required (as mentioned in #437) we could still distinguish by the Accept header whether to return a zip file with all screenshots or a json with all urls.

**Comment by bruderol** [comment]
I still agree on the need to get all screenshots of one scenario (as a ZIP), but:
1. there is allready a different view and different endpoint for this
2. the endpoint for getting a scenario with all its steps is not the objectRepository --> needs special solution on the scenario resource (not the object repository resource)

**Comment by adiherzog** [comment]
@bruderol @Stivo Should this PR go into release 2.2 or not? I did not read all the discussions above. Does it need to be changed or is it ok as it is now?

**Comment by bruderol** [comment]
@adiherzog @Stivo 

I am not sure if the REST URL is now correct.

If it is 
/rest/branch/{branchName}/build/{buildName}/object/{type}/{objectName}/screenshots 
then it is okay for me and can be merged from my point of view.

we could still add a test later.

It will not harm release 2.2 in any way and I would recommend to merge it therefore.

But take care, this PR is for develop branch not yet for release branch.

**Comment by Stivo** [comment]
I think the URL is good. For now our tool that needs this rest service hasn't been started yet, so there is no immediate need for the PR to be in this release. When would be the next release?

**Comment by bruderol** [comment]
next release 2.2 is next week.
After that I guess that the full text search will be the next release.

**Comment by Stivo** [comment]
Well yes, don't stop the release on our account. The same team that would implement this tool will also implement the full text search, so they will need a working fork in any case.

**Comment by adiherzog** [comment]
The URL in the PR is currently:

`/rest/branch/{branchName}/build/{buildName}/screens/{type}/{name}/`

... but Rolf would like to have:

`/rest/branch/{branchName}/build/{buildName}/object/{type}/{objectName}/screenshots`

@bruderol Is this good enough or should it be changed?

**Comment by adiherzog** [comment]
We do not merge this in version 2.2 as there is no urgent need, but we can merge it into develop soon for future releases.

**Comment by bruderol** [comment]
@adiherzog I think we should also merge that one for the next release. I guess the last thing missing was a test.

**Comment by bruderol** [comment]
@adiherzog please also merge that for next release! or is it included in the other full text search PR?

**Comment by bruderol** [comment]
@adiherzog I assogned you, to take care that this gets also merged properly. Thanks.

**Comment by bruderol** [comment]
@adiherzog Können wir den jetzt auch mergen? Oder gar nicht mehr nötig?

**Comment by bruderol** [comment]
@Stivo Do you still need this? Should we include it in our next release? coming soon ...

**Comment by Stivo** [comment]
I honestly don't know. I left this project end of June, so you would have to talk to @featureenvy or someone from the Team.

**Comment by bruderol** [comment]
Ok, so @featureenvy and @adiherzog do we still have to merge this or was it included in the ofther full text search branch allready?  I think we should merge that too for the next release. Any objections?

**Comment by featureenvy** [comment]
I sneaked this into the 18-search branch. :)

So a variant of this REST endpoint is already in Scenarioo.

**Comment by bruderol** [comment]
@featureenvy aha, I allmost expected something like that ;-) an easter egg ;-)
somehow I didnt see it in the review. aha, okay, now I see it, yesterday I did not find it somehow. sorry.

**Comment by bruderol** [comment]
Ok, I checked and the version by @featureenvy looks 99% to conform to what we have here on this PR.

Just one thing:
The URL is not the same as in this MR and I do not like it: /rest/branch/{branchName}/build/{buildName}/object/{type}/{objectName}/**relatedstep**

I think that `relatedSteps` would be better (it does not just return one step). What do you think?

Proposal: Let's change the URL in existing code and then close this MR here, since code seems to be allready merged.

**Comment by bruderol** [comment]
closing because it was allready merged from full text search fork.

**Pull request closed without merging**
