### PR TITLE
Fixes chrome version

### PR DESCRIPTION
**Pull request by danielsuter**

### CODE REVIEW

**Review by davidlahner — CHANGES_REQUESTED** [review]
in circle-ci/config.yml there is still the old image used on line 8 (circleci/openjdk:8-jdk-browsers), is this on purpose?

**Comment by danielsuter** [comment]
@eggerschwiler Good catch, that was a merge fail.

**Review by bruderol — APPROVED** [review]
top 👍 Danke!!

**Comment by bruderol** [comment]
@eggerschwiler I guess this can be merged? what you think?

**Review by davidlahner — APPROVED** [review]

**Pull request merged**
